Разметка и графика главной страницы
htmlacademy-htmlcss/1712611-technomart-30 pull request #2
Opened 2021-01-27 21:05 UTC by Irina-Melnik

2021-01-28 01:10 UTC, vladpovelitsa requested changes
Есть несколько моментов, на которые стоит обратить внимание, но в целом всё хорошо, особенно как для новичка :) Так держать!

Не могу пока принять работу, т.к. нужно внести пару правок и закончить верстку остальной страницы https://prnt.sc/xqbnee

2021-01-28 01:10 UTC, vladpovelitsa commented on index.html
> +        <p></p>Настоящие мужские игрушки</p>
тег р открывается и сразу закрывается - поправь опечатку

2021-01-28 01:10 UTC, vladpovelitsa commented on index.html
> +              <--Стоит ли весь этот элемент li оборачивать в ссылку?-->
Это нужно проверить по ТЗ, должен ли весь блок быть кликабельным, если да, то посмотри как правильно согласовать вложенность тегов через сервис https://caninclude.glitch.me/

2021-01-28 01:10 UTC, vladpovelitsa commented on index.html
> +        <--Не разобралась со слайдером-->
давай назначим консультацию, попробую тебе подробнее объяснить

2021-01-30 21:19 UTC, Irina-Melnik commented
Влад, привет!

Я запушила обновления в свой мастер. 
Пулреквест №2 у меня еще не подтвержден, не понимаю, как создать новый пулреквест. Или может быть мои обновления автоматически подцепились к существующему пулреквесту? Если обновления не видны, подскажи, пожалуйста, что делать.

2021-02-04 08:50 UTC, vladpovelitsa approved these changes
По разметке я проблем не вижу, всё поправила, молодец! 
Есть небольшой момент по графике, я не помню, чтобы об этом упоминалось на трансляции, поэтому скорее всего это не твоё упущение, но все же поправить этому нужно: в некоторых картинках ты использовала в названии заглавные буквы и/или пробелы, от этого нужно избавиться, т.к. пока ты делает на локальном ПК всё ок, но при размещении сайта на сервере могут быть проблемы, т.к. чаще всего они не видят такие символы. Так что тебе нужно будет заменит все заглавные буквы на строчные и пробелы заменить на _ (нижнее подчеркивание) или - (дефикс), как тебе больше нравится :)

2021-02-04 08:50 UTC, merged